// <auto-generated />
using System;
using HotelManagementSystems.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelManagementSystems.Migrations
{
    [DbContext(typeof(HotelManagementDbContext))]
    [Migration("20190126015255_Hotel1")]
    partial class Hotel1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelManagementSystems.Models.Amentities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Amentities");
                });

            modelBuilder.Entity("HotelManagementSystems.Models.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("ID");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("HotelManagementSystems.Models.Hotel_Room", b =>
                {
                    b.Property<decimal>("RoomID");

                    b.Property<int>("HotelID");

                    b.Property<bool>("PetFriendly");

                    b.Property<decimal>("Rate");

                    b.Property<int?>("RoomID1");

                    b.Property<int>("RoomNumber");

                    b.HasKey("RoomID", "HotelID");

                    b.HasIndex("HotelID");

                    b.HasIndex("RoomID1");

                    b.ToTable("HotelRooms");
                });

            modelBuilder.Entity("HotelManagementSystems.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("RoomAmentitiesID");

                    b.Property<int>("Roomlayout");

                    b.HasKey("ID");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("HotelManagementSystems.Models.RoomAmentities", b =>
                {
                    b.Property<int>("AmentitiesID");

                    b.Property<int>("RoomID");

                    b.HasKey("AmentitiesID", "RoomID");

                    b.HasIndex("AmentitiesID")
                        .IsUnique();

                    b.HasIndex("RoomID")
                        .IsUnique();

                    b.ToTable("RoomAmentities");
                });

            modelBuilder.Entity("HotelManagementSystems.Models.Hotel_Room", b =>
                {
                    b.HasOne("HotelManagementSystems.Models.Hotel", "Hotel")
                        .WithMany("Room")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HotelManagementSystems.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID1");
                });

            modelBuilder.Entity("HotelManagementSystems.Models.RoomAmentities", b =>
                {
                    b.HasOne("HotelManagementSystems.Models.Amentities", "Amentities")
                        .WithOne("RoomAmentities")
                        .HasForeignKey("HotelManagementSystems.Models.RoomAmentities", "AmentitiesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HotelManagementSystems.Models.Room", "Room")
                        .WithOne("RoomAmentities")
                        .HasForeignKey("HotelManagementSystems.Models.RoomAmentities", "RoomID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
